# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Deploy in EC2
        env:
          PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY  }}
          HOSTNAME: ${{ secrets.REMOTE_HOST  }}
          USER_NAME: ${{ secrets.REMOTE_USER  }}

        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
          ls

          #Now we have got the access of EC2 and we will start the deploy .
          #cd /home/ubuntu/CounterApp &&
          #git checkout master &&
          #git fetch --all &&
          #git reset --hard origin/master &&
          #git pull origin master &&
